FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

ARG DOCKER_USER=jenkins
ARG UID=1000
ARG GID=1000

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y -o Acquire::Retries=10 \
        devscripts \
        equivs \
        curl \
        gcc-8 \
        g++-8 \
        clang \
        clang-tools \
        libarchive-dev \
        software-properties-common \
        sudo \
        wget

# nodejs (more recent version needed for building libqt-jami)
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt install nodejs -y

ADD extras/packaging/gnu-linux/scripts/prebuild-package-debian.sh /opt/prebuild-package-debian.sh

COPY extras/packaging/gnu-linux/rules/debian-qt/control /tmp/builddeps/debian/control
RUN /opt/prebuild-package-debian.sh qt-deps

COPY extras/packaging/gnu-linux/rules/debian/control /tmp/builddeps/debian/control
RUN /opt/prebuild-package-debian.sh jami-deps

RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# Install CMake 3.19 for Qt 6
ADD extras/packaging/gnu-linux/scripts/install-cmake.sh /opt/install-cmake.sh
RUN /opt/install-cmake.sh

RUN groupadd -g ${GID} ${DOCKER_USER} || true
RUN useradd -m -u "${UID}" -g "${GID}" "${DOCKER_USER}"
RUN usermod -a -G sudo ${DOCKER_USER}
RUN chown -R ${UID}:${GID} /opt
USER ${DOCKER_USER}
WORKDIR /home/${DOCKER_USER}

ADD extras/packaging/gnu-linux/scripts/build-package-debian.sh /opt/build-package-debian.sh
CMD ["/opt/build-package-debian.sh"]
